import {U,C} from './data.js';
const $=s=>document.querySelector(s);
const E={f:$('#field'),fx:$('#fx'),toast:$('#toast'),title:$('#title'),k:$('#kicker'),obj:$('#objective'),turn:$('#turn'),phase:$('#phase'),hint:$('#hint'),atk:$('#attack'),skill:$('#skill'),wait:$('#wait'),undo:$('#undo'),end:$('#end'),prev:$('#preview'),card:$('#unitcard'),side:$('#side'),terrain:$('#terrain'),terrainInfo:$('#terraininfo'),ally:$('#ally'),enemy:$('#enemy'),limit:$('#limit'),short:$('#shortobj'),score:$('#score'),log:$('#log'),tp:$('#talkPortrait'),sp:$('#speaker'),talk:$('#talk'),list:$('#chapterList')};
const T={p:['平原','plain',1,0,'基础地形。'],f:['树林','forest',2,.15,'防御 +15%，骑兵移动额外受限。'],h:['高地','hill',2,.25,'防御 +25%，适合远程守军。'],r:['河流','river',99,0,'多数兵种不可通行。'],b:['桥梁','bridge',1,0,'狭窄通道，容易形成卡口。'],g:['关隘','gate',1,.30,'防御 +30%，适合据守。'],v:['村庄','village',1,.10,'防御 +10%，回合结束恢复 HP。']};
const S={ci:0,turn:1,phase:'ally',units:[],sel:null,mode:'idle',origin:null,over:false,unlock:1};
const ch=()=>C[S.ci],alive=u=>u.hp>0,at=(x,y)=>S.units.find(u=>alive(u)&&u.x===x&&u.y===y),D=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y),K=(x,y)=>y*14+x,tm=(x,y)=>T[ch().grid[y][x]];
function clone(id,x,y,role,side){const t=JSON.parse(JSON.stringify(U[id]));return {...t,id,uid:id+Math.random().toString(36).slice(2,8),x,y,role,side,hp:t.h,maxhp:t.h,mp:t.p,maxmp:t.p,acted:false,cd:0,buff:{},lv:t.f==='wei'?5:4}}
const SPR={cao:0,dun:1,yuan:2,ren:3,xun:4,inf:5,spear:6,archer:7,zhangbao:8,hua:9,lubu:10,yanliang:11};
function sprite(s){const d=document.createElement('div');d.className='sprite '+s;const a=document.createElement('span');a.className='unitSprite';a.style.backgroundPosition=(-32*(SPR[s]??5))+'px 0px';d.append(a);return d}
function unitDom(u){const w=document.createElement('div');w.className='unit '+(u.side==='enemy'?'enemy ':'')+(u.acted?'acted':'');const n=document.createElement('span');n.className='name';n.textContent=u.n;w.append(n,sprite(u.s));const h=document.createElement('div');h.className='hp';h.innerHTML='<i style="width:'+Math.max(0,100*u.hp/u.maxhp)+'%"></i>';w.append(h);if(u.cd){const c=document.createElement('span');c.className='cd';c.textContent=u.cd;w.append(c)}return w}
function talk(name,s,text){E.sp.textContent=name;E.talk.textContent=text;E.tp.innerHTML='';E.tp.append(sprite(s))}
function log(s){const d=document.createElement('div');d.innerHTML='<b>·</b> '+String(s).replace(/[<>]/g,'');E.log.prepend(d);while(E.log.children.length>18)E.log.lastChild.remove()}
function toast(s){E.toast.textContent=s;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1100)}
function start(i){S.ci=i;S.turn=1;S.phase='ally';S.sel=null;S.mode='idle';S.origin=null;S.over=false;S.units=[];ch().a.forEach(([id,x,y])=>S.units.push(clone(id,x,y,'player','ally')));ch().e.forEach(([id,x,y,r])=>S.units.push(clone(id,x,y,r,'enemy')));E.log.innerHTML='';log('战斗开始：'+ch().obj);talk(...ch().talk);render();closeModal('chapterModal')}
function render(){E.f.innerHTML='';for(let y=0;y<10;y++)for(let x=0;x<14;x++){const t=tm(x,y),b=document.createElement('div');b.className='cell-hitbox '+t[1];b.style.position='absolute';b.style.left=(x*100/14)+'%';b.style.top=(y*10)+'%';b.style.width=(100/14)+'%';b.style.height='10%';const u=at(x,y);if(u)b.append(unitDom(u));if(S.sel?.uid===u?.uid)b.classList.add('selected');if(S.sel&&!S.sel.acted&&S.phase==='ally'){if(S.mode==='move'&&reach(S.sel).has(K(x,y))&&!u)b.classList.add('move');if(S.mode==='target'&&u&&targets(S.sel,false).includes(u))b.classList.add('target');if(S.mode==='skill'&&u&&targets(S.sel,true).includes(u))b.classList.add('skilltarget')}b.onclick=()=>clickTile(x,y);b.onmouseenter=()=>showTerrain(x,y);E.f.append(b)}E.k.textContent=ch().no+' · '+ch().sub;E.title.textContent=ch().ti;E.obj.textContent=ch().obj;E.turn.textContent='第 '+S.turn+' 回合';E.phase.textContent=S.phase==='ally'?'我军阶段':'敌军阶段';const a=S.units.filter(u=>u.side==='ally'&&alive(u)).length,e=S.units.filter(u=>u.side==='enemy'&&alive(u)).length;E.ally.textContent=a;E.enemy.textContent=e;E.score.textContent=a+' : '+e;E.limit.textContent=ch().lim;E.short.textContent=ch().short;renderCard();commands()}
function renderCard(){const u=S.sel;if(!u){E.side.textContent='未选择';E.card.className='muted';E.card.textContent='点击武将查看信息。';return}E.side.textContent=u.side==='ally'?'我军':'敌军';E.card.className='';const sk=u.sk?`<div class="skillline"><b>${u.sk.n}</b>　MP ${u.sk.mp}　冷却 ${u.sk.cd} 回合<br>${u.sk.t}<br>当前：${u.cd?'还需 '+u.cd+' 回合':'可使用'}</div>`:'';E.card.innerHTML=`<div class="profile"><div class="portrait med"></div><div><strong>${u.n}</strong><small>Lv.${u.lv} · ${u.cn} · ${u.w}</small><label>HP <b>${u.hp}/${u.maxhp}</b></label><div class="bar"><i style="width:${100*u.hp/u.maxhp}%"></i></div><label>MP <b>${u.mp}/${u.maxmp}</b></label><div class="bar mp"><i style="width:${u.maxmp?100*u.mp/u.maxmp:0}%"></i></div></div></div><div class="stats"><span>攻击 ${atkStat(u)}</span><span>防御 ${defStat(u)}</span><span>精神 ${u.i}</span><span>敏捷 ${u.g}</span><span>移动 ${u.m}</span><span>射程 ${u.r[0]}–${u.r[1]}</span></div>${sk}`;E.card.querySelector('.portrait').append(sprite(u.s))}
function commands(){const u=S.sel,ok=u&&u.side==='ally'&&!u.acted&&S.phase==='ally'&&!S.over;E.atk.disabled=!ok;E.wait.disabled=!ok;E.undo.disabled=!(ok&&S.origin&&(u.x!==S.origin.x||u.y!==S.origin.y));E.skill.disabled=!(ok&&u.sk&&u.cd===0&&u.mp>=u.sk.mp);E.end.disabled=S.phase!=='ally'||S.over;E.hint.textContent=S.over?'战斗已经结束。':S.phase==='enemy'?'敌军正在行动……':!u?'选择我军武将开始行动。':S.mode==='move'?'选择蓝色区域移动。':S.mode==='target'?'选择攻击目标。':S.mode==='skill'?'选择技能目标。':'选择行动指令。'}
function showTerrain(x,y){const t=tm(x,y);E.terrain.textContent=t[0];E.terrainInfo.textContent=t[4]+' 移动消耗 '+(t[2]>90?'不可通行':t[2])+'。'}
function cost(u,x,y){let c=tm(x,y)[2];if(c>90)return c;if((u.c==='cavalry'||u.c==='mountedArcher')&&['f','h'].includes(ch().grid[y][x]))c++;return c}
function reach(u){const out=new Map([[K(u.x,u.y),0]]),q=[[u.x,u.y,0]];while(q.length){const [x,y,c]=q.shift();for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>13||ny>9)continue;const nc=c+cost(u,nx,ny);if(nc>u.m)continue;const o=at(nx,ny);if(o&&!(nx===u.x&&ny===u.y))continue;const k=K(nx,ny);if(!out.has(k)||nc<out.get(k)){out.set(k,nc);q.push([nx,ny,nc])}}}out.delete(K(u.x,u.y));return out}
function targets(u,skill){if(skill&&u.sk?.k==='buff')return[u];const r=skill?u.sk.r:u.r;return S.units.filter(v=>alive(v)&&v.side!==u.side&&D(u,v)>=r[0]&&D(u,v)<=r[1])}
function select(u){S.sel=u;S.mode='move';S.origin={x:u.x,y:u.y};talk(u.n,u.s,'末将在！');render()}
function clickTile(x,y){if(S.over||S.phase!=='ally')return;const u=at(x,y);if(S.mode==='target'||S.mode==='skill'){const skill=S.mode==='skill';if(u&&targets(S.sel,skill).includes(u)){doAttack(S.sel,u,skill);return}toast('目标不在有效范围内');return}if(!S.sel){if(u&&u.side==='ally'&&!u.acted)select(u);else if(u){S.sel=u;render()}return}if(u&&u.side==='ally'&&!u.acted){if(S.origin){S.sel.x=S.origin.x;S.sel.y=S.origin.y}select(u);return}if(S.mode==='move'&&!u&&reach(S.sel).has(K(x,y))){S.sel.x=x;S.sel.y=y;S.mode='action';talk(S.sel.n,S.sel.s,'已到位，请下令。');render();return}if(u&&u.side==='enemy'){S.sel=u;render()}}
function mult(a,d){if(a.c==='cavalry'&&d.c==='infantry')return 1.28;if(a.c==='infantry'&&d.c==='archer')return 1.25;if(a.c==='archer'&&d.c==='cavalry')return 1.30;if(a.c==='mountedArcher'&&d.c==='cavalry')return 1.22;if(a.c==='spear'&&d.c==='cavalry')return 1.35;return 1}
function atkStat(u){return Math.round(u.a*(u.buff.weak?0.78:1))}function defStat(u){return Math.round(u.d*(u.buff.wall?1.4:1))}
function damage(a,b,skill=false){const t=tm(b.x,b.y),m=mult(a,b),pow=skill?(a.sk?.pow||1):1;if(skill&&a.sk?.k==='fire')return Math.max(10,Math.round((a.i*1.25-b.i*.35)+20));return Math.max(7,Math.round((atkStat(a)*pow-defStat(b)*(1+t[3])*.72)*m+15))}
function pop(u,d){const r=E.f.getBoundingClientRect(),cw=r.width/14,ch=r.height/10,n=document.createElement('b');n.className='dmg';n.style.left=((u.x+.5)*cw-12)+'px';n.style.top=((u.y+.5)*ch-18)+'px';n.textContent='-'+d;E.fx.append(n);setTimeout(()=>n.remove(),800)}
function doAttack(a,b,skill){if(skill){if(!a.sk||a.cd||a.mp<a.sk.mp)return;a.mp-=a.sk.mp;a.cd=a.sk.cd+1;if(a.sk.k==='buff'){a.buff.wall=2;log(a.n+' 使用【'+a.sk.n+'】。');finish();return}}const d=damage(a,b,skill);b.hp=Math.max(0,b.hp-d);pop(b,d);log(a.n+(skill?' 使用【'+a.sk.n+'】':' 攻击')+' → '+b.n+' '+d+' 伤害');if(skill&&a.sk?.k==='fire')for(const v of S.units.filter(v=>alive(v)&&v.side!==a.side&&v!==b&&D(v,b)===1)){const sd=Math.round(d*.55);v.hp=Math.max(0,v.hp-sd);pop(v,sd)}if(b.hp<=0)log(b.n+' 被击败。');check();finish()}
function finish(){if(S.sel&&S.sel.side==='ally')S.sel.acted=true;S.sel=null;S.mode='idle';S.origin=null;check();render()}
function check(){const cao=S.units.find(u=>u.id==='cao'&&u.side==='ally');if(!cao||cao.hp<=0){S.over=true;talk('战败','cao','大业未成……');toast('战败');return true}if(ch().ai.protect){const p=S.units.find(u=>u.id===ch().ai.protect&&u.side==='ally');if(!p||p.hp<=0){S.over=true;toast('战败：保护目标阵亡');return true}}const boss=S.units.find(u=>u.role==='boss'&&u.side==='enemy');if(!boss||boss.hp<=0){S.over=true;S.unlock=Math.max(S.unlock,Math.min(C.length,S.ci+2));localStorage.setItem('cc-unlock',String(S.unlock));talk('曹操','cao','此战已定。整军，准备下一役。');toast('胜利！');return true}if(S.turn>ch().lim){S.over=true;toast('战败：超过回合限制');return true}return false}
function bestMove(u,target){let best={x:u.x,y:u.y,d:D(u,target)};for(const k of reach(u).keys()){const x=k%14,y=Math.floor(k/14),d=Math.abs(x-target.x)+Math.abs(y-target.y);if(d<best.d)best={x,y,d}}return best}
async function enemyTurn(){S.phase='enemy';S.sel=null;render();for(const u of S.units.filter(v=>v.side==='enemy'&&alive(v))){if(S.over)break;const allies=S.units.filter(v=>v.side==='ally'&&alive(v));if(!allies.length)break;let target=allies.sort((a,b)=>D(u,a)-D(u,b))[0];if(D(u,target)<u.r[0]||D(u,target)>u.r[1]){if(u.role!=='sniper'&&u.role!=='boss'||S.turn>2){const m=bestMove(u,target);u.x=m.x;u.y=m.y}}target=S.units.filter(v=>v.side==='ally'&&alive(v)).sort((a,b)=>D(u,a)-D(u,b))[0];if(target&&D(u,target)>=u.r[0]&&D(u,target)<=u.r[1]){const d=damage(u,target,false);target.hp=Math.max(0,target.hp-d);pop(target,d);log(u.n+' 攻击 '+target.n+' '+d+' 伤害');if(target.hp<=0)log(target.n+' 被击败。')}render();await new Promise(r=>setTimeout(r,160));check()}if(!S.over){S.turn++;S.phase='ally';for(const u of S.units){u.acted=false;if(u.cd>0)u.cd--;if(u.buff.wall){u.buff.wall--;if(!u.buff.wall)delete u.buff.wall}if(u.side==='ally'&&alive(u)&&ch().grid[u.y][u.x]==='v')u.hp=Math.min(u.maxhp,u.hp+12)}render()}}
function chapters(){E.list.innerHTML='';C.forEach((c,i)=>{const b=document.createElement('button');b.className='chap'+(i>=S.unlock?' locked':'');b.disabled=i>=S.unlock;b.innerHTML=`<span>${c.no}</span><b>${c.ti}</b><p>${c.sub} · ${c.short}</p>`;if(!b.disabled)b.onclick=()=>start(i);E.list.append(b)});$('#chapterModal').classList.remove('hide')}
function closeModal(id){$('#'+id)?.classList.add('hide')}
E.atk.onclick=()=>{if(S.sel){S.mode='target';render()}};E.skill.onclick=()=>{if(S.sel?.sk){S.mode='skill';render()}};E.wait.onclick=finish;E.undo.onclick=()=>{if(S.sel&&S.origin){S.sel.x=S.origin.x;S.sel.y=S.origin.y;S.mode='move';render()}};E.end.onclick=enemyTurn;$('#restart').onclick=()=>start(S.ci);$('#chapters').onclick=chapters;$('#rules').onclick=()=>$('#ruleModal').classList.remove('hide');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));
try{S.unlock=Math.max(1,Math.min(C.length,Number(localStorage.getItem('cc-unlock'))||1))}catch{}
start(0);
