import {U,C} from './data.js';
const $=s=>document.querySelector(s),E={f:$('#field'),fx:$('#fx'),toast:$('#toast'),title:$('#title'),k:$('#kicker'),obj:$('#objective'),turn:$('#turn'),phase:$('#phase'),hint:$('#hint'),atk:$('#attack'),skill:$('#skill'),wait:$('#wait'),undo:$('#undo'),end:$('#end'),prev:$('#preview'),card:$('#unitcard'),side:$('#side'),terrain:$('#terrain'),terrainInfo:$('#terraininfo'),ally:$('#ally'),enemy:$('#enemy'),limit:$('#limit'),short:$('#shortobj'),score:$('#score'),log:$('#log'),tp:$('#talkPortrait'),sp:$('#speaker'),talk:$('#talk'),list:$('#chapterList')};
const T={p:['平原','plain',1,0,'基础地形。'],f:['树林','forest',2,.15,'防御 +15%，骑兵移动额外受限。'],h:['高地','hill',2,.25,'防御 +25%，适合远程守军。'],r:['河流','river',99,0,'多数兵种不可通行。'],b:['桥梁','bridge',1,0,'狭窄通道，容易形成卡口。'],g:['关隘','gate',1,.3,'防御 +30%，适合据守。'],v:['村庄','village',1,.1,'防御 +10%，回合结束恢复 HP。']};
const S={ci:0,turn:1,phase:'ally',units:[],sel:null,mode:'idle',origin:null,preview:null,over:false,unlock:1};
const ch=()=>C[S.ci],alive=u=>u.hp>0,at=(x,y)=>S.units.find(u=>alive(u)&&u.x===x&&u.y===y),D=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y),K=(x,y)=>y*14+x,tm=(x,y)=>T[ch().grid[y][x]];
function clone(id,x,y,role,side){let t=structuredClone(U[id]);return {...t,id,uid:id+Math.random().toString(36).slice(2,7),x,y,role,side,hp:t.h,maxhp:t.h,mp:t.p,maxmp:t.p,acted:false,cd:0,buff:{},lv:t.f==='wei'?5:4}}
function start(i){S.ci=i;S.turn=1;S.phase='ally';S.sel=null;S.mode='idle';S.origin=null;S.preview=null;S.over=false;S.units=[];ch().a.forEach(([id,x,y])=>S.units.push(clone(id,x,y,'player','ally')));ch().e.forEach(([id,x,y,r])=>S.units.push(clone(id,x,y,r,'enemy')));E.log.innerHTML='';log('战斗开始：'+ch().obj);talk(...ch().talk);render();close('chapterModal')}
function sprite(s){let d=document.createElement('div');d.className='sprite '+s;d.innerHTML='<i class="cape"></i><i class="body"></i><i class="head"></i><i class="helm"></i><i class="weapon"></i><i class="blade"></i>';return d}
function unitDom(u){let w=document.createElement('div');w.className='unit '+(u.side==='enemy'?'enemy ':'')+(u.acted?'acted':'');let n=document.createElement('span');n.className='name';n.textContent=u.n;w.append(n,sprite(u.s));let h=document.createElement('div');h.className='hp';h.innerHTML='<i style="width:'+100*u.hp/u.maxhp+'%"></i>';w.append(h);if(u.cd){let c=document.createElement('span');c.className='cd';c.textContent=u.cd;w.append(c)}return w}
function render(){E.f.innerHTML='';for(let y=0;y<10;y++)for(let x=0;x<14;x++){let t=tm(x,y),b=document.createElement('button');b.className='tile '+t[1];b.type='button';let u=at(x,y);if(u)b.append(unitDom(u));if(S.sel?.uid===u?.uid)b.classList.add('selected');if(S.sel&&!S.sel.acted&&S.phase==='ally'){if(S.mode==='move'&&reach(S.sel).has(K(x,y))&&!u)b.classList.add('move');if(S.mode==='target'&&u&&targets(S.sel,false).includes(u))b.classList.add('target');if(S.mode==='skill'&&u&&targets(S.sel,true).includes(u))b.classList.add('skilltarget')}b.onclick=()=>clickTile(x,y);b.onmouseenter=()=>showTerrain(x,y);E.f.append(b)}E.k.textContent=ch().no+' · '+ch().sub;E.title.textContent=ch().ti;E.obj.textContent=ch().obj;E.turn.textContent='第 '+S.turn+' 回合';E.phase.textContent=S.phase==='ally'?'我军阶段':'敌军阶段';let a=S.units.filter(u=>u.side==='ally'&&alive(u)).length,e=S.units.filter(u=>u.side==='enemy'&&alive(u)).length;E.ally.textContent=a;E.enemy.textContent=e;E.score.textContent=a+' : '+e;E.limit.textContent=ch().lim;E.short.textContent=ch().short;renderCard();commands()}
function renderCard(){let u=S.sel;if(!u){E.side.textContent='未选择';E.card.className='muted';E.card.textContent='点击武将查看信息。';return}E.side.textContent=u.side==='ally'?'我军':'敌军';E.card.className='';let sk=u.sk?`<div class="skillline"><b>${u.sk.n}</b>　MP ${u.sk.mp}　冷却 ${u.sk.cd} 回合<br>${u.sk.t}<br>当前：${u.cd?'还需 '+u.cd+' 回合':'可使用'}</div>`:'';E.card.innerHTML=`<div class="profile"><div class="portrait med"></div><div><strong>${u.n}</strong><small>Lv.${u.lv} · ${u.cn} · ${u.w}</small><label>HP <b>${u.hp}/${u.maxhp}</b></label><div class="bar"><i style="width:${100*u.hp/u.maxhp}%"></i></div><label>MP <b>${u.mp}/${u.maxmp}</b></label><div class="bar mp"><i style="width:${u.maxmp?100*u.mp/u.maxmp:0}%"></i></div></div></div><div class="stats"><span>攻击 ${atkStat(u)}</span><span>防御 ${defStat(u)}</span><span>精神 ${u.i}</span><span>敏捷 ${u.g}</span><span>移动 ${u.m}</span><span>射程 ${u.r[0]}–${u.r[1]}</span></div>${sk}`;E.card.querySelector('.portrait').append(sprite(u.s))}
function commands(){let u=S.sel,ok=u&&u.side==='ally'&&!u.acted&&S.phase==='ally'&&!S.over;E.atk.disabled=!ok;E.wait.disabled=!ok;E.undo.disabled=!(ok&&S.origin&&(u.x!==S.origin.x||u.y!==S.origin.y));E.skill.disabled=!(ok&&u.sk&&u.cd===0&&u.mp>=u.sk.mp);E.end.disabled=S.phase!=='ally'||S.over;E.hint.textContent=S.over?'战斗已经结束。':S.phase==='enemy'?'敌军正在行动……':!u?'选择我军武将开始行动。':S.mode==='move'?'蓝框为可移动区域。':S.mode==='target'?'选择红框敌军。':S.mode==='skill'?'选择紫框技能目标。':'选择行动指令。'}
function showTerrain(x,y){let t=tm(x,y);E.terrain.textContent=t[0];E.terrainInfo.textContent=t[4]+' 移动消耗 '+(t[2]>90?'不可通行':t[2])+'。'}
function talk(name,s,text){E.sp.textContent=name;E.talk.textContent=text;E.tp.innerHTML='';E.tp.append(sprite(s))}function log(s){let d=document.createElement('div');d.innerHTML='<b>·</b> '+s.replace(/[<>]/g,'');E.log.prepend(d);while(E.log.children.length>18)E.log.lastChild.remove()}function toast(s){E.toast.textContent=s;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1200)}
function cost(u,x,y){let t=tm(x,y),c=t[2];if(c>90)return c;if((u.c==='cavalry'||u.c==='mountedArcher')&&['f','h'].includes(ch().grid[y][x]))c++;return c}
function reach(u){let out=new Map([[K(u.x,u.y),0]]),q=[[u.x,u.y,0]];while(q.length){let [x,y,c]=q.shift();for(let [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>13||ny>9)continue;let nc=c+cost(u,nx,ny);if(nc>u.m)continue;let o=at(nx,ny);if(o&&!(nx===u.x&&ny===u.y))continue;let k=K(nx,ny);if(!out.has(k)||nc<out.get(k)){out.set(k,nc);q.push([nx,ny,nc])}}}out.delete(K(u.x,u.y));return out}
function targets(u,skill){if(skill&&u.sk?.k==='buff')return[u];let r=skill?u.sk.r:u.r;return S.units.filter(v=>alive(v)&&v.side!==u.side&&D(u,v)>=r[0]&&D(u,v)<=r[1])}
function select(u){S.sel=u;S.mode='move';S.origin={x:u.x,y:u.y};talk(u.n,u.s,'末将在！');render()}
function clickTile(x,y){if(S.over||S.phase!=='ally'||S.preview)return;let u=at(x,y);if(['target','skill'].includes(S.mode)){if(u&&targets(S.sel,S.mode==='skill').includes(u))return preview(S.sel,u,S.mode==='skill');return toast('目标不在有效范围内')}if(!S.sel){if(u&&u.side==='ally'&&!u.acted)select(u);return}if(u&&u.side==='ally'&&!u.acted){if(S.origin){S.sel.x=S.origin.x;S.sel.y=S.origin.y}select(u);return}if(S.mode==='move'&&!u&&reach(S.sel).has(K(x,y))){S.sel.x=x;S.sel.y=y;S.mode='action';talk(S.sel.n,S.sel.s,'已到位，请下令。');render();return}if(u&&u.side==='enemy'){S.sel=u;render()}}
function mult(a,d){if(a.c==='cavalry'&&d.c==='infantry')return 1.28;if(a.c==='infantry'&&d.c==='archer')return 1.25;if(a.c==='archer'&&d.c==='cavalry')return 1.3;if(a.c==='mountedArcher'&&d.c==='cavalry')return 1.22;if(a.c==='spear'&&d.c==='cavalry')return 1.35;return 1}
function atkStat(u){return Math.round(u.a*(u.buff.weak?0.78:1))}function defStat(u){return Math.round(u.d*(u.buff.wall?1.4:1))}
function est(a,b,skill){let t=tm(b.x,b.y),m=mult(a,b),pow=skill?(a.sk.pow||1):1,base=skill&&a.sk.k==='fire'?Math.max(10,(a.i*1.25-b.i*.35)+20):Math.max(7,(atkStat(a)*pow-defStat(b)*(1+t[3])*.72)*m+15);return{d:Math.round(base),hit:Math.max(58,Math.min(99,Math.round(88+(a.g-b.g)*.7))),crit:Math.max(4,Math.min(28,Math.round(7+(a.g-b.g)*.35))),m,t}}
function preview(a,b,skill){S.preview=b;let e=est(a,b,skill);E.prev.classList.remove('hide');E.prev.innerHTML=`<div class="pre"><div><b>${a.n} → ${b.n}</b><p>${skill?'技能【'+a.sk.n+'】':'普通攻击'}　伤害 ${Math.max(1,e.d-5)}–${e.d+5}　命中 ${e.hit}%　暴击 ${e.crit}% ${e.m>1?'<em>兵种克制 ×'+e.m.toFixed(2)+'</em>':''}<br>目标地形：${e.t[0]}，防御 +${Math.round(e.t[3]*100)}%</p></div><button id="back">返回</button><button id="go">确认</button></div>`;$('#back').onclick=()=>{S.preview=null;E.prev.classList.add('hide');render()};$('#go').onclick=async()=>{E.prev.classList.add('hide');await attack(a,b,skill);finish()}}
async function attack(a,b,skill){if(skill){a.mp-=a.sk.mp;a.cd=a.sk.cd+1;if(a.sk.k==='buff'){a.buff.wall=2;log(a.n+' 使用【'+a.sk.n+'】，进入铁壁状态。');await fx(a,a,'fire');return}}let e=est(a,b,skill);await fx(a,b,skill?a.sk.k:(['archer','mountedArcher'].includes(a.c)?'arrow':'strike'));if(Math.random()*100>e.hit){log(a.n+' 的攻击被 '+b.n+' 闪避。');return toast('MISS')}let d=e.d+Math.floor(Math.random()*11)-5,crit=Math.random()*100<e.crit;if(crit)d=Math.round(d*1.5);b.hp=Math.max(0,b.hp-d);pop(b,d,crit);log(a.n+(skill?' 使用【'+a.sk.n+'】':' 攻击')+' → '+b.n+' '+d+' 伤害'+(e.m>1?'（克制）':'')+(crit?'（暴击）':''));if(skill&&a.sk.k==='strike')b.buff.weak=1;if(skill&&a.sk.k==='fire')for(let v of S.units.filter(v=>alive(v)&&v.side!==a.side&&v!==b&&D(v,b)===1)){let sd=Math.round(d*.55);v.hp=Math.max(0,v.hp-sd);pop(v,sd,false);log(v.n+' 受到溅射 '+sd+' 伤害')}if(b.hp<=0){log(b.n+' 被击败。');return check()}if((!skill||a.sk.k!=='arrow')&&D(a,b)>=b.r[0]&&D(a,b)<=b.r[1]){let ce=est(b,a,false);if(Math.random()*100<ce.hit){await fx(b,a,['archer','mountedArcher'].includes(b.c)?'arrow':'strike');let cd=Math.max(5,Math.round(ce.d*.62));a.hp=Math.max(0,a.hp-cd);pop(a,cd,false);log(b.n+' 反击 '+a.n+' '+cd+' 伤害')}}check()}
function finish(){if(S.sel)S.sel.acted=true;S.sel=null;S.mode='idle';S.origin=null;S.preview=null;check();render()}
function check(){let cao=S.units.find(u=>u.id==='cao'&&u.side==='ally');if(!cao||cao.hp<=0){S.over=true;toast('战败：曹操阵亡');talk('战败','cao','大业未成……');return true}if(ch().ai.protect){let p=S.units.find(u=>u.id===ch().ai.protect&&u.side==='ally');if(!p||p.hp<=0){S.over=true;toast('战败：保护目标阵亡');return true}}let boss=S.units.find(u=>u.role==='boss'&&u.side==='enemy');if(!boss||boss.hp<=0){S.over=true;S.unlock=Math.max(S.unlock,Math.min(C.length,S.ci+2));try{localStorage.setItem('cc-unlock',S.unlock)}catch{}toast('胜利！下一章已解锁');talk('曹操','cao','此战已定。整军，准备下一役。');return true}if(S.turn>ch().lim){S.over=true;toast('战败：超过回合限制');return true}return false}
function center(u){let r=E.f.getBoundingClientRect(),c=r.width/14;return{x:(u.x+.5)*c,y:(u.y+.5)*c}}function pop(u,d,c){let p=center(u),n=document.createElement('b');n.className='dmg';n.style.left=p.x-12+'px';n.style.top=p.y-18+'px';n.textContent=(c?'暴击 ':'-')+d;E.fx.append(n);setTimeout(()=>n.remove(),850)}function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function fx(a,b,k){let A=center(a),B=center(b);if(k==='arrow'){let n=document.createElement('i');n.className='arrowfx';let dx=B.x-A.x,dy=B.y-A.y;n.style.left=A.x+'px';n.style.top=A.y+'px';n.style.width=Math.max(14,Math.hypot(dx,dy)*.22)+'px';n.style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;E.fx.append(n);let an=n.animate([{translate:'0 0'},{translate:`${dx}px ${dy}px`}],{duration:360,easing:'ease-out'});await an.finished;n.remove()}else{let n=document.createElement('i');n.className=k==='fire'?'firefx':'slashfx';n.style.left=B.x-(k==='fire'?23:27)+'px';n.style.top=B.y-(k==='fire'?45:27)+'px';E.fx.append(n);await sleep(k==='fire'?600:340);n.remove()}}
function activated(u){let a=ch().ai;if(u.role==='aggressive')return true;if(u.role==='reserve')return S.turn>=a.hold+2;if(S.turn>=a.hold)return true;let allies=S.units.filter(v=>v.side==='ally'&&alive(v));return (a.x!=null&&allies.some(v=>v.x>=a.x))||(a.y!=null&&allies.some(v=>v.y<=a.y))}
function tscore(u,x,y,t){let m=tm(x,y),s=m[3]*35-D({x,y},t)*4;if(u.role==='sniper'){let d=D({x,y},t);if(d>=u.r[0]&&d<=u.r[1])s+=30;if(['h','g'].includes(ch().grid[y][x]))s+=18}if(u.role==='choke'&&['g','b'].includes(ch().grid[y][x]))s+=35;if(['guard','boss'].includes(u.role)){let z=ch().ai.zone;if(z&&x>=z[0]&&x<=z[2]&&y>=z[1]&&y<=z[3])s+=22;else if(z)s-=22}if(u.hp/u.maxhp<.35&&ch().grid[y][x]==='v')s+=42;return s}
function targetScore(u,t){return 100-D(u,t)*7-(t.hp/t.maxhp)*20+(mult(u,t)-1)*90+(t.id==='cao'?8:0)+(ch().ai.protect===t.id?20:0)}function aiTargets(u){return S.units.filter(v=>v.side==='ally'&&alive(v)).sort((a,b)=>targetScore(u,b)-targetScore(u,a))}
function bestMove(u,t){let o=[{x:u.x,y:u.y,s:tscore(u,u.x,u.y,t)}];for(let k of reach(u).keys()){let x=k%14,y=Math.floor(k/14);o.push({x,y,s:tscore(u,x,y,t)})}for(let p of o){let d=D(p,t);p.s+=d>=u.r[0]&&d<=u.r[1]?32:-Math.abs(d-u.r[1])*5}return o.sort((a,b)=>b.s-a.s)[0]}
async function enemyTurn(){if(S.over)return;S.phase='enemy';S.sel=null;S.mode='idle';render();await sleep(300);for(let u of S.units.filter(u=>u.side==='enemy'&&alive(u))){if(S.over)break;if(!activated(u)){log(u.n+' 继续坚守 '+tm(u.x,u.y)[0]+'。');continue}let ts=aiTargets(u);if(!ts.length)break;let t=ts[0],m=bestMove(u,t);if(m.x!==u.x||m.y!==u.y){u.x=m.x;u.y=m.y;render();await sleep(190)}let rr=aiTargets(u).filter(t=>D(u,t)>=u.r[0]&&D(u,t)<=u.r[1]);if(rr.length){await attack(u,rr[0],false);render();await sleep(230)}}for(let u of S.units.filter(alive))if(ch().grid[u.y][u.x]==='v'){let h=Math.round(u.maxhp*.18),b=u.hp;u.hp=Math.min(u.maxhp,u.hp+h);if(u.hp>b)log(u.n+' 在村庄恢复 '+(u.hp-b)+' HP')}if(!S.over){S.turn++;S.phase='ally';for(let u of S.units.filter(u=>u.side==='ally'&&alive(u))){u.acted=false;if(u.cd)u.cd--;for(let k in u.buff)if(u.buff[k])u.buff[k]--}talk('曹操','cao','观察敌阵，不要浪费地形优势。');check();render()}}
function modal(id){$('#'+id).classList.remove('hide')}function close(id){$('#'+id).classList.add('hide')}function chapterList(){E.list.innerHTML='';C.forEach((c,i)=>{let b=document.createElement('button');b.className='chap '+(i>=S.unlock?'locked':'');b.disabled=i>=S.unlock;b.innerHTML=`<span>${c.no} · ${c.sub}</span><b>${c.ti}</b><p>${c.obj}</p>`;b.onclick=()=>start(i);E.list.append(b)})}
E.atk.onclick=()=>{S.mode='target';render()};E.skill.onclick=()=>{if(S.sel?.sk?.k==='buff')attack(S.sel,S.sel,true).then(finish);else{S.mode='skill';render()}};E.wait.onclick=finish;E.undo.onclick=()=>{S.sel.x=S.origin.x;S.sel.y=S.origin.y;S.mode='move';render()};E.end.onclick=enemyTurn;$('#restart').onclick=()=>start(S.ci);$('#chapters').onclick=()=>{chapterList();modal('chapterModal')};$('#rules').onclick=()=>modal('ruleModal');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)close(m.id)});
try{S.unlock=Math.max(1,Math.min(C.length,Number(localStorage.getItem('cc-unlock')||1)))}catch{}start(0);